reviews:
  namespace: student28-bookinfo-dev
  image: ghcr.io/earndiva/bookinfo-reviews
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student28/reviews(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-dev-reviews-mongodb:27017/reviews
  MONGO_DB_USERNAME: reviews
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-dev-reviews-mongodb-secret: mongodb-password